updated workflow to use environment : DEV

diff --git a/.github/workflows/a2_korosol_dev.yml b/.github/workflows/a2_korosol_dev.yml
--- a/.github/workflows/a2_korosol_dev.yml
+++ b/.github/workflows/a2_korosol_dev.yml
@@ -15,6 +15,7 @@ env:
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
+    environment: DEV
     strategy:
       matrix:
         include:
@@ -134,14 +135,14 @@ jobs:
       run: |
         sshpass -p "${{ env.SSH_PASSWORD }}" ssh -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no \
           ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
-          "echo Connected as: $(whoami) && touch /home/hduque/DEV_THINGS/dotnet/kobflow/github_actions_delivery/Expense/test.txt && echo 'Write succeeded!' || echo 'Write failed!'"
+          "echo Connected as: \$(whoami) && touch /home/hduque/DEV_THINGS/dotnet/kobflow/github_actions_delivery/Expense/test.txt && echo 'Write succeeded!' || echo 'Write failed!'"
   
     - name: 🛑 Stop remote service before deploy
       if: steps.changes.outputs.changed == 'true'
       run: |
         sshpass -p "${{ env.SSH_PASSWORD }}" ssh -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no \
           ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
-          "sudo systemctl stop kobflow-${{ matrix.name }}.service || true"  
+          "sudo systemctl stop ${{ vars.SERVICE_PREFIX }}.${{ matrix.name }}.service || true"  
 
 
     - name: 🚀 Deploy ${{ matrix.name }}
@@ -150,6 +151,13 @@ jobs:
         sshpass -p "${{ env.SSH_PASSWORD }}" scp -P ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no -r \
           publish/${{ matrix.name }}/* \
           ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:/home/hduque/DEV_THINGS/dotnet/kobflow/github_actions_delivery/${{ matrix.name }}/
+
+    - name: ▶️ Restart remote service
+      if: steps.changes.outputs.changed == 'true'
+      run: |
+        sshpass -p "${{ env.SSH_PASSWORD }}" ssh -p ${{ env.SSH_PORT }} -o StrictHostKeyChecking=no \
+          ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
+           "sudo systemctl start ${{ vars.SERVICE_PREFIX }}.${{ matrix.name }}.service"
 
     - name: ✅ Verify deployment
       if: steps.changes.outputs.changed == 'true'
